name: imagenes-por-fecha-nasa

#EVENTO
on:
  push:
    branches:
      - prueba

#JOBS
jobs:

  #JOB 1
  consumo_api:
    name: imagen por fecha
    runs-on: ubuntu-latest #RUNNER
    #LOGICA
    strategy:
      fail-fast: false
      matrix:
        fechas: [fecha_uno, fecha_dos, fecha_3]

    #STEP 1
    steps:
      - name: consumo api por fecha
        run: #SHELL

